version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: reviews-postgres
    environment:
      POSTGRES_USER: reviews_user
      POSTGRES_PASSWORD: reviews_pass
      POSTGRES_DB: reviews_db
    ports:
      - "5432:5432"
    volumes:
      - reviews-db-data:/var/lib/postgresql/data

  reviews-service:
    image: hishampk1/reviews-service:1.0.0
    container_name: reviews-service-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reviews_db
      SPRING_DATASOURCE_USERNAME: reviews_user
      SPRING_DATASOURCE_PASSWORD: reviews_pass
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  reviews-db-data:
