apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: cloudshelf
data:
  NEXT_PUBLIC_API_BASE_URL: "http://k8s-cloudshe-cloudshe-796e07ef43-1342598769.us-east-1.elb.amazonaws.com/api"
  NEXT_PUBLIC_API_GATEWAY_URL: "http://k8s-cloudshe-cloudshe-796e07ef43-1342598769.us-east-1.elb.amazonaws.com/api/graphql"
  NEXT_PUBLIC_USE_DUMMY_DATA: "false"
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
